services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn code_runner.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: code_runner.settings
      - key: PYTHON_VERSION
        value: 3.10

