services:
  - type: web
    name: post-drag-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn code_runner.wsgi:application --chdir=code_runner"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: code_runner.settings
      - key: PYTHON_VERSION
        value: 3.11

